services:
  postgres:
    image: postgres:16-alpine
    container_name: ew-pgdb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart:   unless-stopped
  
  redis:
    image: redis:7
    container_name: ew-redis
    volumes:
      -  redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  
  api-gateway:
    build: ../services/api-gateway-service
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - auth-service
      - user-service
      - todo-service
    restart:   unless-stopped

  auth-service:
    build: ../services/auth-service
    depends_on:
      - postgres
      - redis
    restart:   unless-stopped

  user-service:
    build: ../services/user-service
    depends_on:
      - postgres
    restart:   unless-stopped

  todo-service:
    build: ../services/todo-service
    depends_on:
      - postgres
    restart:   unless-stopped

  notification-service:
    build: ../services/notification-service
    depends_on:
      - postgres
    restart:   unless-stopped

  google-calendar-service:
    build: ../services/google-calendar-service
    depends_on:
      - postgres
    restart:   unless-stopped


volumes:
  pgdata: 
    driver: local
  redisdata:
    driver: local

