# DOCKER COMPOSE FILE FOR DEVELOPMENT ENVIRONMENT
name: electra-whale-dev

services:

  # ---------------------------------------------------------------------------
  # INFRASTRUCTURE (Database and Cache)
  # ---------------------------------------------------------------------------

  postgres:
    image: postgres:16-alpine
    container_name: ew-pgdb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart:   unless-stopped
  
  redis:
    image: redis:7
    container_name: ew-redis
    volumes:
      -  redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"

  # ---------------------------------------------------------------------------
  # MICROSERVICES
  # ---------------------------------------------------------------------------

  # === API GATEWAY ===
  api-gateway:
    build: 
      context: ..
      dockerfile: services/api-gateway-service/Dockerfile.dev
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - auth-service
      - user-service
      - todo-service
    environment:
      - USER_SERVICE_PORT=${USER_PORT}
      - AUTH_SERVICE_PORT=${AUTH_PORT}
      - TODO_SERVICE_PORT=${TODO_PORT}
      - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_PORT}
      - GOOGLE_CALENDAR_SERVICE_PORT=${GOOGLE_CALENDAR_PORT}
      - JWT_SECRET=${AUTH_JWT_SECRET}
    volumes:
      - ../services/api-gateway-service:/app/services/api-gateway-service
      - ../packages/common:/app/packages/common
      - /app/services/api-gateway-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: npm run dev

  # === AUTHENTICATION SERVICE ===
  auth-service:
    build: 
      context: ..
      dockerfile: services/auth-service/Dockerfile.dev
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES}
    expose:
      - "${AUTH_PORT}"
    volumes:
      - ../services/auth-service:/app/services/auth-service
      - ../packages/common:/app/packages/common
      # Mantemos os node_modules isolados para nÃ£o haver conflito com o host
      - /app/services/auth-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: >
      sh -c "
      ./wait-for-it.sh postgres:5432 -t 30 -- \
      prisma generate --config=../../packages/common/prisma.config.ts && \
      prisma migrate deploy --config=../../packages/common/prisma.config.ts && \
      
      npm run dev
      "


  # === USER SERVICE ===
  user-service:
    build: 
      context: ..
      dockerfile: services/user-service/Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES}
    volumes:
      - ../services/user-service:/app/services/user-service
      - ../packages/common:/app/packages/common
      - /app/services/user-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: > 
      sh -c "./wait-for-it.sh postgres:5432 -t 60 -- 
      prisma generate --config=../../packages/common/prisma.config.ts && 
      npm run dev"


  # === TODO SERVICE ===
  todo-service:
    build: 
      context: ..
      dockerfile: services/todo-service/Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES}
    volumes:
      - ../services/todo-service:/app/services/todo-service
      - ../packages/common:/app/packages/common
      - /app/services/todo-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: >
      sh -c "./wait-for-it.sh postgres:5432 -t 60 -- 
      prisma generate --config=../../packages/common/prisma.config.ts && 
      npm run dev"


  # === NOTIFICATION SERVICE ===
  notification-service:
    build: 
      context: ..
      dockerfile: services/notification-service/Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES}
    volumes:
      - ../services/notification-service:/app/services/notification-service
      - ../packages/common:/app/packages/common
      - /app/services/notification-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: >
      sh -c "./wait-for-it.sh postgres:5432 -t 60 -- 
      prisma generate --config=../../packages/common/prisma.config.ts && 
      npm run dev"


  # === GOOGLE CALENDAR SERVICE ===
  google-calendar-service:
    build: 
      context: ..
      dockerfile: services/google-calendar-service/Dockerfile.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES}
    volumes:
      - ../services/google-calendar-service:/app/services/google-calendar-service
      - ../packages/common:/app/packages/common
      - /app/services/google-calendar-service/node_modules
      - /app/packages/common/node_modules
      - /app/node_modules
    command: >  
      sh -c "./wait-for-it.sh postgres:5432 -t 60 -- 
      prisma generate --config=../../packages/common/prisma.config.ts && 
      npm run dev"


  # -----------------------------
  # VOLUMES
  # -----------------------------

volumes:
  pgdata: 
    driver: local
    name: ew_pgdata
  redisdata:
    driver: local
    name: ew_redisdata